CREATE TABLE IMGFILE(
PK INT PRIMARY KEY,
TITLE VARCHAR(50),
FILENAME VARCHAR(50)
);

DROP TABLE IMGFILE;

INSERT INTO IMGFILE(PK,TITLE) VALUES((SELECT NVL(MAX(PK),0)+1 FROM IMGFILE),'Á¦¸ñ2');
SELECT * FROM IMGFILE;
DELETE * FROM IMGFILE;

create table asdf{
date date
}